# Generated by Django 5.0 on 2024-01-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_booking_booking_date_alter_booking_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.SmallAutoField(primary_key=True, serialize=False),
        ),
    ]
